/**
 * audioMap.js — AUTO-GENERATED by scripts/generate_audio.js
 * Maps "style:text" → "/assets/audio/filename.mp3"
 * DO NOT EDIT MANUALLY — run: node scripts/generate_audio.js
 */
const audioMap = {
  "celebration:Ready to master place value? Let's go!": "/assets/audio/celebration_ready_to_master_place_value_let_s_go.mp3",
  "statement:Join Hundy, Tenny, and Onesy and discover how every number is secretly made of hundreds, tens, and ones — through stories, simulations, and exciting games!": "/assets/audio/statement_join_hundy_tenny_and_onesy_and_discover_how_every_number_is_secretly_m.mp3",
  "question:A number has 4 hundreds, 7 tens, and 2 ones. What is its expanded form?": "/assets/audio/question_a_number_has_4_hundreds_7_tens_and_2_ones_what_is_its_expanded_form.mp3",
  "thinking:What if we need to show the value of each digit separately?": "/assets/audio/thinking_what_if_we_need_to_show_the_value_of_each_digit_separately.mp3",
  "emphasis:Every digit has its own special place value!": "/assets/audio/emphasis_every_digit_has_its_own_special_place_value.mp3",
  "statement:Meet Hundy, Tenny, and Onesy — three robot crew members who live inside every 3-digit number. They show how numbers are built from hundreds, tens, and ones!": "/assets/audio/statement_meet_hundy_tenny_and_onesy_three_robot_crew_members_who_live_inside_ev.mp3",
  "statement:Every 3-digit number has three special homes — Hundreds on the left, Tens in the middle, Ones on the right. Hundy loves Hundreds, Tenny loves Tens, and Onesy loves Ones!": "/assets/audio/statement_every_3_digit_number_has_three_special_homes_hundreds_on_the_left_tens.mp3",
  "emphasis:The 3 in 358 is in the Hundreds place, so it means 300. The 5 is in the Tens place, so it means 50. The 8 is in the Ones place, so it means 8. So 358 equals 300 plus 50 plus 8!": "/assets/audio/emphasis_the_3_in_358_is_in_the_hundreds_place_so_it_means_300_the_5_is_in_the_t.mp3",
  "statement:We can go the other way too! If you see 400 plus 70 plus 2, just add the parts: 400 plus 70 equals 470, then 470 plus 2 equals 472. Expanded form and standard form show the same number!": "/assets/audio/statement_we_can_go_the_other_way_too_if_you_see_400_plus_70_plus_2_just_add_the.mp3",
  "instruction:Welcome to the Block Builder! Use the plus and minus buttons to place hundreds, tens, and ones blocks until the total matches the target number.": "/assets/audio/instruction_welcome_to_the_block_builder_use_the_plus_and_minus_buttons_to_place.mp3",
  "instruction:Count the fuel groups, then write the expanded form. Each crate holds 100 fuel cells, each tube holds 10, and each loose cell is just 1!": "/assets/audio/instruction_count_the_fuel_groups_then_write_the_expanded_form_each_crate_holds_.mp3",
  "celebration:You're a Digit Detective! Tap a digit from the number, then tap the correct place-value house to drop it in. Match all three digits to complete the mission!": "/assets/audio/celebration_you_re_a_digit_detective_tap_a_digit_from_the_number_then_tap_the_co.mp3",
  "question:The rocket has landed on a number on the number line. Decode its expanded form by filling in the hundreds, tens, and ones values!": "/assets/audio/question_the_rocket_has_landed_on_a_number_on_the_number_line_decode_its_expande.mp3",
  "celebration:Welcome to the Galaxy Quiz! Answer questions correctly to earn stars and build your streak. Let's go, Place Value Pioneer!": "/assets/audio/celebration_welcome_to_the_galaxy_quiz_answer_questions_correctly_to_earn_stars_.mp3",
  "celebration:Fantastic! That's exactly right!": "/assets/audio/celebration_fantastic_that_s_exactly_right.mp3",
  "celebration:Brilliant! You know your place values!": "/assets/audio/celebration_brilliant_you_know_your_place_values.mp3",
  "celebration:Perfect! Keep that streak going!": "/assets/audio/celebration_perfect_keep_that_streak_going.mp3",
  "celebration:Amazing work, Place Value Pioneer!": "/assets/audio/celebration_amazing_work_place_value_pioneer.mp3",
  "celebration:Yes! Hundy, Tenny and Onesy are cheering for you!": "/assets/audio/celebration_yes_hundy_tenny_and_onesy_are_cheering_for_you.mp3",
  "celebration:Superb! You really understand expanded form!": "/assets/audio/celebration_superb_you_really_understand_expanded_form.mp3",
  "encouragement:Not quite, but you're learning! Check each place value.": "/assets/audio/encouragement_not_quite_but_you_re_learning_check_each_place_value.mp3",
  "encouragement:Almost! Remember: hundreds on the left, ones on the right.": "/assets/audio/encouragement_almost_remember_hundreds_on_the_left_ones_on_the_right.mp3",
  "encouragement:Good try! Every mistake helps us learn more!": "/assets/audio/encouragement_good_try_every_mistake_helps_us_learn_more.mp3",
  "encouragement:Keep going! Hundy, Tenny and Onesy believe in you!": "/assets/audio/encouragement_keep_going_hundy_tenny_and_onesy_believe_in_you.mp3",
  "encouragement:Don't worry — take a look at the explanation and try the next one!": "/assets/audio/encouragement_don_t_worry_take_a_look_at_the_explanation_and_try_the_next_one.mp3",
  "celebration:Mission complete, Galaxy Champion! You finished the quiz and proved you know expanded form inside and out!": "/assets/audio/celebration_mission_complete_galaxy_champion_you_finished_the_quiz_and_proved_yo.mp3",
  "celebration:Amazing work completing Place Value Pioneers! You've mastered expanded form — breaking numbers into hundreds, tens, and ones!": "/assets/audio/celebration_amazing_work_completing_place_value_pioneers_you_ve_mastered_expande.mp3",
  "emphasis:You can now write any 3-digit number in expanded form and read it like a true place value expert!": "/assets/audio/emphasis_you_can_now_write_any_3_digit_number_in_expanded_form_and_read_it_like_.mp3",
  "question:What does the 6 mean in 634?": "/assets/audio/question_what_does_the_6_mean_in_634.mp3",
  "question:Write 509 in expanded form.": "/assets/audio/question_write_509_in_expanded_form.mp3",
  "question:What number equals 300 plus 40 plus 8?": "/assets/audio/question_what_number_equals_300_plus_40_plus_8.mp3",
  "question:Which digit is in the tens place in 726?": "/assets/audio/question_which_digit_is_in_the_tens_place_in_726.mp3",
  "celebration:Amazing! That's exactly right! 300 plus 50 plus 7 is the expanded form!": "/assets/audio/celebration_amazing_that_s_exactly_right_300_plus_50_plus_7_is_the_expanded.mp3",
  "encouragement:Good try! The answer is 300 plus 50 plus 7. Each digit shows its place value!": "/assets/audio/encouragement_good_try_the_answer_is_300_plus_50_plus_7_each_digit_shows.mp3"
};
export default audioMap;
